In [1]:
import pandas as pd
import numpy as np
df = pd.read_csv('C:/Users/david/Documents/0_kul/1_ma_stds_1/1_advanced_analytics/assignment_2/data/meaningful/recipe_without_empty.csv')

In [6]:
keep = ['tag_chocolate', 'tag_pasta', 'tag_chicken','tag_cheese','tag_salad','tag_pizza','tag_coffee','tag_lemon',
       'tag_avocado','tag_banana','tag_steak','tag_strawberry']

In [7]:
keep_2 = ['photo_id', 'url', 'may_be', 'likes', 'timestamp', 'scraped_at', 'diff'] + keep

In [9]:
df_recipe = df[keep_2]
df = df_recipe[(df_recipe.iloc[:,7:11].T != 0).any()] # keep only relevant pictures
df.head(10)

,photo_id,url,may_be,likes,timestamp,scraped_at,diff,tag_chocolate,tag_pasta,tag_chicken,tag_cheese,tag_salad,tag_pizza,tag_coffee,tag_lemon,tag_avocado,tag_banana,tag_steak,tag_strawberry
4,CMPD73jJssJ,https://www.instagram.com/p/CMPD73jJssJ/,dessert,2,2021-03-10T10:45:12,2021-03-10T11:49:16,1.07,1,0,0,0,0,0,0,0,0,0,0,0
7,CMPD1lBJbbq,https://www.instagram.com/p/CMPD1lBJbbq/,food,2,2021-03-10T10:44:20,2021-03-10T11:49:34,1.09,0,0,0,1,1,0,0,0,0,0,0,0
14,CMPDn1oDxJA,https://www.instagram.com/p/CMPDn1oDxJA/,food and indoor,26,2021-03-10T10:42:44,2021-03-10T11:50:07,1.12,0,1,0,1,0,0,0,0,0,0,0,0
16,CMPDgtknaSS,https://www.instagram.com/p/CMPDgtknaSS/,cake and indoor,3,2021-03-10T10:41:29,2021-03-10T11:50:21,1.15,1,1,0,0,0,0,0,0,0,0,0,0
18,CMPDgGEFXA5,https://www.instagram.com/p/CMPDgGEFXA5/,indoor,7,2021-03-10T10:41:24,2021-03-10T11:50:30,1.15,0,0,0,1,1,0,0,0,0,0,0,0
19,CMPDfbQnqDF,https://www.instagram.com/p/CMPDfbQnqDF/,dessert,4,2021-03-10T10:41:19,2021-03-10T11:50:34,1.15,0,1,0,0,0,0,0,0,0,0,0,0
28,CMPC5ODlMip,https://www.instagram.com/p/CMPC5ODlMip/,food and indoor,3,2021-03-10T10:36:06,2021-03-10T11:51:35,1.26,0,1,0,0,0,0,0,0,0,0,0,0
34,CMNXtGhpVew,https://www.instagram.com/p/CMNXtGhpVew/,pasta,125,2021-03-09T21:03:06,2021-03-10T11:52:27,14.82,0,1,0,1,0,0,0,0,0,0,0,0
35,CMMqLGmBzII,https://www.instagram.com/p/CMMqLGmBzII/,pasta,47,2021-03-09T12:21:36,2021-03-11T16:47:46,52.44,0,1,0,1,0,0,0,0,0,0,0,0
36,CMPCmZdHCcY,https://www.instagram.com/p/CMPCmZdHCcY/,chow mein and indoor,2,2021-03-10T10:33:32,2021-03-10T11:52:49,1.32,0,0,1,0,0,0,0,0,0,0,0,0

In [10]:
y = df[keep]
y.head(5)

,tag_chocolate,tag_pasta,tag_chicken,tag_cheese,tag_salad,tag_pizza,tag_coffee,tag_lemon,tag_avocado,tag_banana,tag_steak,tag_strawberry
4,1,0,0,0,0,0,0,0,0,0,0,0
7,0,0,0,1,1,0,0,0,0,0,0,0
14,0,1,0,1,0,0,0,0,0,0,0,0
16,1,1,0,0,0,0,0,0,0,0,0,0
18,0,0,0,1,1,0,0,0,0,0,0,0

In [11]:
y.iloc[0].sum()
list = []

In [12]:
for i in range(0,200):
    result = y.iloc[i].sum()
    list.append(result)

In [17]:
print(list)

[1, 2, 2, 2, 2, 1, 1, 2, 2, 1, 1, 1, 3, 1, 1, 1, 2, 1, 1, 1, 2, 2, 1, 1, 2, 1, 2, 1, 1, 2, 1, 1, 1, 2, 2, 1, 2, 1, 2, 1, 1, 3, 3, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 2, 2, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1, 1, 2, 1, 2, 1, 1, 1]

In [23]:
print(y.shape)
print(df.shape)

(1493, 12)
(1493, 19)

In [26]:
y.to_csv("C:/Users/david/Documents/0_kul/1_ma_stds_1/1_advanced_analytics/assignment_2/data/meaningful/y.csv",index=False)

In [27]:
df.to_csv("C:/Users/david/Documents/0_kul/1_ma_stds_1/1_advanced_analytics/assignment_2/data/meaningful/df.csv",index=False)